// Auto-generated by scripts/analyze_gaps.py --export
// Re-run to refresh. Do not edit manually.
window.CSA_GAP_DATA = {
  "generatedAt": "2026-04-03T15:46:12",
  "summary": {
    "assessed": 25,
    "gaps": 24,
    "atTarget": 1
  },
  "domains": [
    {
      "domain": "Azure Networking",
      "current": 3,
      "target": 4,
      "gap": 1,
      "evidence": "",
      "phase": 1,
      "weeks": [
        1,
        2
      ],
      "slot": "A",
      "focus": "VNets, subnets, NSGs, peering, DNS, private endpoints, routing"
    },
    {
      "domain": "Identity & Access Management",
      "current": 3,
      "target": 4,
      "gap": 1,
      "evidence": "",
      "phase": 1,
      "weeks": [
        1,
        2
      ],
      "slot": "A",
      "focus": "Entra ID, RBAC, managed identity, conditional access, PIM"
    },
    {
      "domain": "Infrastructure as Code",
      "current": 3,
      "target": 5,
      "gap": 2,
      "evidence": "",
      "phase": 1,
      "weeks": [
        1,
        2
      ],
      "slot": "A",
      "focus": "Bicep, Terraform, ARM, azd, module design"
    },
    {
      "domain": "Azure Landing Zones",
      "current": 2,
      "target": 4,
      "gap": 2,
      "evidence": "",
      "phase": 1,
      "weeks": [
        2
      ],
      "slot": "A",
      "focus": "Enterprise-scale, management groups, governance hierarchy"
    },
    {
      "domain": "Azure Policy & Compliance",
      "current": 2,
      "target": 4,
      "gap": 2,
      "evidence": "",
      "phase": 1,
      "weeks": [
        2
      ],
      "slot": "A",
      "focus": "Policy definitions, initiatives, compliance reporting, remediation"
    },
    {
      "domain": "Network Security",
      "current": 2,
      "target": 4,
      "gap": 2,
      "evidence": "",
      "phase": 5,
      "weeks": [
        9,
        10
      ],
      "slot": "A",
      "focus": "Azure Firewall, DDoS, WAF, NSGs, private endpoints, zero-trust network"
    },
    {
      "domain": "Application Security",
      "current": 3,
      "target": 4,
      "gap": 1,
      "evidence": "",
      "phase": 5,
      "weeks": [
        9,
        10
      ],
      "slot": "A",
      "focus": "Key Vault, secret rotation, encryption, certificate management"
    },
    {
      "domain": "Microsoft Defender for Cloud",
      "current": 2,
      "target": 3,
      "gap": 1,
      "evidence": "",
      "phase": 5,
      "weeks": [
        9
      ],
      "slot": "C",
      "focus": "Security posture, Secure Score, recommendations, threat protection"
    },
    {
      "domain": "Azure Kubernetes Service",
      "current": 2,
      "target": 4,
      "gap": 2,
      "evidence": "",
      "phase": 5,
      "weeks": [
        9,
        10
      ],
      "slot": "A",
      "focus": "Cluster design, networking (CNI), scaling, GitOps, KEDA"
    },
    {
      "domain": "Azure Container Apps",
      "current": 2,
      "target": 3,
      "gap": 1,
      "evidence": "",
      "phase": 5,
      "weeks": [
        10
      ],
      "slot": "B",
      "focus": "Microservices, Dapr, KEDA, ingress, environments"
    },
    {
      "domain": "Azure Functions & Serverless",
      "current": 3,
      "target": 4,
      "gap": 1,
      "evidence": "",
      "phase": 3,
      "weeks": [
        5,
        6
      ],
      "slot": "C",
      "focus": "Trigger types, bindings, Durable Functions, Flex Consumption"
    },
    {
      "domain": "Azure App Service",
      "current": 4,
      "target": 4,
      "gap": 0,
      "evidence": "",
      "phase": 3,
      "weeks": [
        5
      ],
      "slot": "C",
      "focus": "Web apps, deployment slots, autoscale, App Service Environments"
    },
    {
      "domain": "Azure Storage Services",
      "current": 3,
      "target": 4,
      "gap": 1,
      "evidence": "",
      "phase": 5,
      "weeks": [
        9
      ],
      "slot": "A",
      "focus": "Blob, ADLS Gen2, queues, file shares, access tiers, lifecycle"
    },
    {
      "domain": "Azure SQL & Relational Databases",
      "current": 2,
      "target": 4,
      "gap": 2,
      "evidence": "",
      "phase": 5,
      "weeks": [
        10
      ],
      "slot": "D",
      "focus": "Azure SQL DB, managed instance, elastic pools, failover groups"
    },
    {
      "domain": "Azure Cosmos DB",
      "current": 2,
      "target": 3,
      "gap": 1,
      "evidence": "",
      "phase": 5,
      "weeks": [
        10
      ],
      "slot": "D",
      "focus": "Partition design, consistency levels, APIs, global distribution"
    },
    {
      "domain": "Azure Fabric & Analytics",
      "current": 1,
      "target": 3,
      "gap": 2,
      "evidence": "",
      "phase": 5,
      "weeks": [
        10
      ],
      "slot": "D",
      "focus": "Microsoft Fabric, Synapse, Data Factory, Lakehouse, Delta Lake"
    },
    {
      "domain": "Azure Messaging & Integration",
      "current": 2,
      "target": 4,
      "gap": 2,
      "evidence": "",
      "phase": 5,
      "weeks": [
        9,
        10
      ],
      "slot": "D",
      "focus": "Service Bus, Event Grid, Event Hubs, Logic Apps, event-driven patterns"
    },
    {
      "domain": "Azure API Management",
      "current": 2,
      "target": 4,
      "gap": 2,
      "evidence": "",
      "phase": 4,
      "weeks": [
        8
      ],
      "slot": "D",
      "focus": "Policies, backends, developer portal, rate limiting, AI gateway"
    },
    {
      "domain": "Azure AI Services",
      "current": 2,
      "target": 4,
      "gap": 2,
      "evidence": "",
      "phase": 2,
      "weeks": [
        3,
        4
      ],
      "slot": "B",
      "focus": "AI Search, Document Intelligence, Speech, Vision, Language"
    },
    {
      "domain": "Azure OpenAI & Generative AI",
      "current": 2,
      "target": 4,
      "gap": 2,
      "evidence": "",
      "phase": 2,
      "weeks": [
        3,
        4
      ],
      "slot": "B",
      "focus": "GPT models, embeddings, RAG, AI Foundry, prompt engineering"
    },
    {
      "domain": "Azure Machine Learning",
      "current": 2,
      "target": 3,
      "gap": 1,
      "evidence": "",
      "phase": 2,
      "weeks": [
        4
      ],
      "slot": "B",
      "focus": "Model training, MLOps, managed endpoints, feature store"
    },
    {
      "domain": "Azure Monitor & Observability",
      "current": 3,
      "target": 4,
      "gap": 1,
      "evidence": "",
      "phase": 3,
      "weeks": [
        5,
        6
      ],
      "slot": "C",
      "focus": "Metrics, logs, alerts, workbooks, App Insights, Log Analytics, KQL"
    },
    {
      "domain": "CI/CD & DevOps",
      "current": 3,
      "target": 4,
      "gap": 1,
      "evidence": "",
      "phase": 3,
      "weeks": [
        5,
        6
      ],
      "slot": "C",
      "focus": "GitHub Actions, Azure DevOps, deployment automation, shift-left security"
    },
    {
      "domain": "Cost Management & FinOps",
      "current": 2,
      "target": 3,
      "gap": 1,
      "evidence": "",
      "phase": 3,
      "weeks": [
        6
      ],
      "slot": "C",
      "focus": "Budgets, Cost Advisor, reservations, tagging strategy, FinOps framework"
    },
    {
      "domain": "Architecture Design & Advisory",
      "current": 2,
      "target": 4,
      "gap": 2,
      "evidence": "",
      "phase": 4,
      "weeks": [
        7,
        8
      ],
      "slot": "D",
      "focus": "WAF pillars, design patterns, ADRs, customer communication, design reviews"
    }
  ],
  "weeks": [
    {
      "week": 1,
      "status": "In Progress"
    },
    {
      "week": 2,
      "status": "In Progress"
    },
    {
      "week": 3,
      "status": "In Progress"
    },
    {
      "week": 4,
      "status": "In Progress"
    },
    {
      "week": 5,
      "status": "In Progress"
    },
    {
      "week": 6,
      "status": "In Progress"
    },
    {
      "week": 7,
      "status": "In Progress"
    },
    {
      "week": 8,
      "status": "In Progress"
    },
    {
      "week": 9,
      "status": "In Progress"
    },
    {
      "week": 10,
      "status": "In Progress"
    }
  ]
};
